# Generated by Django 3.1.4 on 2020-12-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PmiLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_id', models.CharField(max_length=50)),
                ('log_name', models.CharField(max_length=50)),
                ('string_id', models.CharField(max_length=50)),
                ('current', models.FloatField(max_length=50)),
                ('voltage', models.FloatField(max_length=50)),
            ],
        ),
    ]
